MLmodel:
    - SeisBench,PhaseNet,original
    - SeisBench,PhaseNet,stead
    - SeisBench,EQT,original
    - SeisBench,EQT,stead
    
overlap_ratio: 0.95
    
rescaling: 
    - 1000
    - 2000
#    - 3000 # AssertionError
#    - 4000

    
frequency: 
    - None
    - [1000, 5000]
    - [2000, 10000]
#     - [200, 5000] # AssertionError


ensemble: pca  # max, pca, semblance, mean, median, prod, ...

pick:
    method: threshold  # threshold, max, peak
    P_threshold: 0.1  # None or number
    S_threshold: 0.2  # None or number

output: all  # pick or prob

prob_sampling_rate: None  # None or float/int

